--MEMBER 테이블 생성
DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    MID NVARCHAR2(30),   --이메일아이디
    MPW NVARCHAR2(20),      --회원비밀번호
    MNAME NVARCHAR2(5),     --회원이름
    MADDR NVARCHAR2(50),    --회원주소
    MNICK NVARCHAR2(20),    --회원닉네임
    MBIRTH DATE,            --회원생년월일
    MGENDER NVARCHAR2(2),   --회원성별
    MPHONE NUMBER,          --회원휴대번호
    MPROFILE NVARCHAR2(200) --회원프로필파일이름
);

--MEMBER 테이블 제약조건
ALTER TABLE MEMBER
ADD CONSTRAINT PK_MID PRIMARY KEY(MID); --회원 아이디 PK
ALTER TABLE MEMBER
MODIFY MPW NOT NULL     --회원비밀번호 NN
MODIFY MNAME NOT NULL   --회원이름 NN
MODIFY MPHONE NOT NULL;  --회원휴대전화 NN
ALTER TABLE MEMBER
ADD CONSTRAINT UK_MNICK UNIQUE(MNICK); --회원닉네임 UNIQUE

--회원게시글(BOARD) 생성
DROP TABLE BOARD;
CREATE TABLE BOARD(
    BMID NVARCHAR2(30),      --게시글 회원이메일
    BDATE DATE,                 --게시글 작성시간
    BCONTENT NVARCHAR2(2000),   --게시글 내용
    BCODE NVARCHAR2(10),        --게시글 코드
    BVIDEO NVARCHAR2(200),       --게시글 영상 파일이름
    BGCODE NVARCHAR2(10)
);

--BOARD 제약조건
ALTER TABLE BOARD
ADD CONSTRAINT FK_BMID_MID FOREIGN KEY(BMID) REFERENCES MEMBER(MID);  --게시글/회원닉네임 FK
ALTER TABLE BOARD
ADD CONSTRAINT PK_BCODE PRIMARY KEY(BCODE); --게시글 코드 PK
ALTER TABLE BOARD
ADD CONSTRAINT FK_BGCODE_GCODE FOREIGN KEY(BGCODE) REFERENCES GROUPPAGE(GCODE);

--BOARDPHOTO(게시글 사진)
DROP TABLE PHOTO;
CREATE TABLE PHOTO(
    PBCODE NVARCHAR2(10),
    PHOTO NVARCHAR2(500)
);

--댓글(REPLY)
DROP TABLE COMM;
CREATE TABLE COMM(
    CMID NVARCHAR2(30),      --댓글 회원닉네임
    CCOMMENT NVARCHAR2(2000),  --댓글내용
    CDATE DATE,                --댓글 작성일
    CCODE NVARCHAR2(10),        --댓글 코드
    CBCODE NVARCHAR2(10)
);

--REPLY 제약조건
ALTER TABLE COMM
ADD CONSTRAINT PK_CCODE PRIMARY KEY(CCODE);       --댓글코드 PK
ALTER TABLE COMM
ADD CONSTRAINT FK_CMID FOREIGN KEY(CMID) REFERENCES MEMBER(MID);  --댓글/회원닉네임 FK
ALTER TABLE COMM
ADD CONSTRAINT FK_CBCODE_BCODE FOREIGN KEY(CBCODE) REFERENCES BOARD(BCODE);

--대댓글(R_REPLY) 생성
DROP TABLE REPLY;
CREATE TABLE REPLY(
    REMID NVARCHAR2(30),     --답글 회원닉네임
    RECOMMENT NVARCHAR2(200),  --답글 내용
    REDATE DATE,               --답글 작성일자
    RECODE NVARCHAR2(10),      --답글 코드
    RECCODE NVARCHAR2(10)      --댓글 코드
);

--REPLY 제약조건
ALTER TABLE REPLY
ADD CONSTRAINT FK_REMID_MID FOREIGN KEY(REMID) REFERENCES MEMBER(MID);    --대댓글 회원닉네임 FK
ALTER TABLE REPLY
ADD CONSTRAINT PK_RECODE PRIMARY KEY(RECODE);     --대댓글코드 PK
ALTER TABLE REPLY
ADD CONSTRAINT FK_RECCODE_CCODE FOREIGN KEY(RECCODE) REFERENCES COMM(CCODE);   --댓글코드 FK


--좋아요(BOARDLIKE) 생성
DROP TABLE BOARDLIKE;
CREATE TABLE BOARDLIKE(
    LICODE NVARCHAR2(10),      --좋아요 게시글코드
    LIMID NVARCHAR2(30)      --좋아요 회원닉네임
);
--BOARDLIKE 제약조건
ALTER TABLE BOARDLIKE
ADD CONSTRAINT FK_LIMID_MID FOREIGN KEY(LIMID) REFERENCES MEMBER(MID);          --좋아요/회원닉네임 FK

select * from boardlike;
--검색어태그#(HASHTAG) 생성
DROP TABLE HASHTAG;
CREATE TABLE HASHTAG(
    TAGNAME NVARCHAR2(20)       --검색어태그
);

--친구목록(FRIEND) 생성
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    FRMID NVARCHAR2(20),      --친구 닉네임
    MYMID NVARCHAR2(20)       --유저 닉네임
);
--FRIEND 제약조건
ALTER TABLE FRIEND
ADD CONSTRAINT FK_FRMID_MID FOREIGN KEY(FRMID) REFERENCES MEMBER(MID);  --친구닉네임/회원닉네임 FK
ALTER TABLE FRIEND
ADD CONSTRAINT FK_MYMID_MID FOREIGN KEY(MYMID) REFERENCES MEMBER(MID);  --유저닉네임/회원닉네임 FK

--그룹페이지(GROUP) 생성
DROP TABLE GROUPPAGE;
CREATE TABLE GROUPPAGE(
    GNAME NVARCHAR2(20),        --그룹명
    GINFO NVARCHAR2(2000),      --그룹소개글
    GPROFILE NVARCHAR2(200),    --그룹프로필사진명
    GMANAGER NVARCHAR2(20),     --그룹관리자 닉네임
    GCODE NVARCHAR2(10)
);

--GROUP 제약조건
ALTER TABLE GROUPPAGE
ADD CONSTRAINT PK_GCODE PRIMARY KEY(GCODE);     --그룹명 PK
ALTER TABLE GROUPPAGE
ADD CONSTRAINT FK_GMANAGER_MID FOREIGN KEY(GMANAGER) REFERENCES MEMBER(MID);    --그룹관리자/회원닉네임 FK


--그룹회원목록(GUSER) 생성
DROP TABLE GUSER;
CREATE TABLE GUSER(
    GUGCODE NVARCHAR2(10), --그룹명
    GUMID NVARCHAR2(30)   --그룹회원목록
);
SELECT * FROM GUSER;
--GUSER 제약조건
ALTER TABLE GUSER
ADD CONSTRAINT FK_GUGCODE_GCODE FOREIGN KEY(GUGCODE) REFERENCES GROUPPAGE(GCODE);   --그룹회원목록 그룹명 FK
ALTER TABLE GUSER
ADD CONSTRAINT FK_GUMID_MID FOREIGN KEY(GUMID) REFERENCES MEMBER(MID);    --그룹회원목록 그룹회원목록 FK


--Q&A 게시글(QNA) 생성
DROP TABLE QNA;
CREATE TABLE QNA(
    QAMID NVARCHAR2(20),      --QNA 회원닉네임
    QAQ NVARCHAR2(2000),        --QNA 질문내용
    QAA NVARCHAR2(2000),        --QNA 답변내용
    QADATE DATE,                --QNA 작성일자
    QACODE NVARCHAR2(10),       --QNA 코드
    QATITLE NVARCHAR2(50)       --QNA 질문제목
);
--QNA 제약조건
ALTER TABLE QNA
ADD CONSTRAINT FK_QAMID_MID FOREIGN KEY(QAMID) REFERENCES MEMBER(MID);  --QNA 회원닉네임 FK
ALTER TABLE QNA
ADD CONSTRAINT PK_QACODE PRIMARY KEY(QACODE);       --QNA 코드 PK



--신고(REPORT) 생성
DROP TABLE REPORT;
CREATE TABLE REPORT(
    REPORTER NVARCHAR2(10),     --신고자
    REASON NVARCHAR2(10),       --신고사유
    REPORTTARGET NVARCHAR2(10), --신고대상
    REPORTDATE DATE             --신고일
);
--REPORT 제약조건
ALTER TABLE REPORT
MODIFY REASON NOT NULL          --신고사유 NN
MODIFY REPORTTARGET NOT NULL;   --신고대상 NN


--chattingRoom 생성
DROP TABLE CHATTINGROOM;
CREATE TABLE CHATTINGROOM(
    ROOMCODE NVARCHAR2(10),
    CHNICK NVARCHAR2(50)
);

--채팅(CHATTING) 생성
DROP TABLE CHATTING;
CREATE TABLE CHATTING(
    CHNICKNAME NVARCHAR2(20),     --채팅 회원 닉네임
    CHCHATTING NVARCHAR2(200),    --채팅 회원 대화내용
    CHDATE DATE,                  --채팅 작성일
    CHROOMCODE NVARCHAR2(10)             --채팅방 코드
);
